apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: config
build:
  local:
    useBuildkit: true
    tryImportMissing: true
  tagPolicy:
    gitCommit:
      ignoreChanges: true # do not add `-dirty` suffix
  artifacts:
    # PLEX
    - image: testimage
      context: .
      docker:
        dockerfile: Dockerfile
    - image: testimage3
      context: .
      docker:
        dockerfile: Dockerfile2
